#! Dockerfile

FROM public.ecr.aws/lambda/python:3.13

COPY src/ ${LAMBDA_TASK_ROOT}/src/
COPY pyproject.toml poetry.lock ${LAMBDA_TASK_ROOT}/

RUN microdnf update -y && \
    microdnf install -y poppler poppler-utils && \
    microdnf clean all

RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --without dev --no-interaction --no-ansi

ENTRYPOINT [ "/lambda-entrypoint.sh" ]
CMD ["handler.handler"]
